version: '3'
services:
  app:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    command: postgres -c 'max_connections=100'
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  # pgadmin:
  #     container_name: pgadmin4
  #     image: dpage/pgadmin4
  #     restart: always
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: admin@email.com
  #       PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
  #     ports:
  #       - 5050:80